# Generated by Django 4.1 on 2024-01-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('approved_limit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_debt', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('emi_paid_on_time', models.IntegerField(default=0)),
                ('date_of_approval', models.DateField()),
                ('end_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
